<?php
$title="Přihlášení";
include ("html_top.phtml");
include ("nav.phtml");

if(!empty($login_err))
{
    echo '<div class="loginError">'.$login_err.'</div>';
}
?>


<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" id="login" method="post">
    <label for="nickname">Přezdívka</label><br>
    <input type="text" name="nickname" id="nickname" placeholder="Přezdívka" required <?php echo
    (!empty($nickname_err)) ? 'je neplatné' : ''?> value="<?php echo $nickname;?>"><br>
    <span class="invalid-feedback"><?php echo $nickname_err;?></span><br>

    <label for="password">Heslo</label><br>
    <input type="password" name="password" id="password" placeholder="Heslo" required <?php echo
    (!empty($password_err)) ? 'je neplatné' : ''?> value="<?php echo $password;?>"><br>
    <span class="invalid-feedback"><?php echo $password_err;?></span><br>
    <input type="submit" value="Přihlásit se">
</form>

<p>Nemáte ještě účet? <a href="register.php">Registrovat se</a></p>

<?php
include("html_bottom.phtml");
?>