</head>
<body>
<header>
    <a href="index.php"><img src="images/anaglyphLogo.png" alt="logo" width="100px" class="logo"></a>
    <h1><strong><?= /** @var TYPE_NAME $title */$title?></strong></h1>
    <nav>
        <ul class="navigace">
            <li><a href="index.php"><Strong>Hlavní stránka</Strong></a></li>
            <?php
            if($_SESSION["administrator"]==1)
                echo '<li><a href="testLogin.php">Test Login</a></li>'; //<!-- TODO - TEMPORARY POZDĚJI VYMAZAT-->
            ?>
            <li><a href=""></a></li>
            <li><a href="author.php">Autor stránky</a></li>
            <!--
            <li><a href=""></a></li>
            -->
        </ul>
    </nav>
    <?php
    if(isset($_SESSION["id"]))
        {
            echo "<a href=users/".$_SESSION["nickname"]."/".'mainPage.php>'.$_SESSION["nickname"]."</a>";
            echo "<a href=logout.php>Odhlásit se</a>";
        }
    else
        echo '<a href="login.php"><strong>Přihlásit se</strong></a>';
    ?>
    <!-- VOLBA JAZYKU -->
</header>