</head>
<body>
<header>
    <a href="index.php"><img src="images/anaglyphLogo.png" alt="logo" width="100" class="logo"></a>
    <h1><strong><?= /** @var TYPE_NAME $title */$title?></strong></h1>
    <nav>
        <ul class="navigace">
            <li><a href="index.php"><Strong>Index</Strong></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href="author.php">Autor stránky</a></li>
            <!--
            <li><a href=""></a></li>
            -->
        </ul>
    </nav>
    <?php
    if(isset($_SESSION["id"]))
    {
        echo "<p>".$_SESSION["nickname"]."</p>";
    }
    else
        echo '<a href="login.php"><strong>Přihlásit se</strong></a>';
    ?>
    <!-- VOLBA JAZYKU -->
</header>