<?php
$title="Registrace";
include ("html_top.phtml");
include ("nav.phtml");
?>
<form id="register" method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
    <label for="nickname">Přezdívka</label><br>
    <input type="text" name="nickname" id="nickname" placeholder="Přezdívka" required <?php echo
    (!empty($nickname_err)) ? 'je neplatné' : ''?> value="<?php echo $nickname;?>"><br>
    <span class="invalid-feedback"><?php echo $nickname_err;?></span><br>

    <label for="email">E-Mail</label><br>
    <input type="email" name="email" id="email" placeholder="E-Mail" required <?php echo
    (!empty($email_err)) ? 'je neplatné' : ''?> value="<?php echo $email;?>"><br>
    <span class="invalid-feedback"><?php echo $email_err;?></span><br>

    <label for="password">Heslo</label><br>
    <input type="password" name="password" id="password" placeholder="Heslo" required <?php echo
    (!empty($password_err)) ? 'je neplatné' : ''?> value="<?php echo $password;?>"><br>
    <span class="invalid-feedback"><?php echo $password_err;?></span><br>

    <label for="confirm_password">Opakovat heslo</label><br>
    <input type="password" name="confirm_password" id="confirm_password" placeholder="Opakovat heslo" required<?php echo
    (!empty($confirm_password_err)) ? 'je neplatné' : ''?> value="<?php echo $confirm_password;?>">
    <span class="invalid-feedback"><?php echo $confirm_password_err;?></span>


    <input type="submit" value="Registrovat se">
</form>

<p>Již máte účet? <a href="login.php"><strong>Přihlásit se</strong></a></p>



<?php
include("html_bottom.phtml");
?>