<?php
$title = "Nastavení";
include("../html_top.phtml");
include("../nav.phtml");




?>
<h2>Profilová ikona</h2>
<form method='post'>
    <table id="settingsPFPSelect">
    <tr>
        <?php

        //Vypsani vsech profilovych ikon
        function labelPFP($pocitadlo) //Vypsání labelů
        {
            switch($pocitadlo)
            {
                case 1:
                    echo "Výchozí";
                    break;
                case 2:
                    echo "Sluneční brýle";
                    break;
                case 3:
                    echo "Heisenberg";
                    break;
                case 4:
                    echo "Jesse Pinkman";
                    break;
                case 5:
                    echo "Patrick Bateman";
                    break;
                case 6:
                    echo "Luke Skywalker";
                    break;
                case 7:
                    echo "Luffy D. Monkey";
                    break;
                case 8:
                    echo "Neko (Krátké vlasy)";
                    break;
                case 9:
                    echo "Neko (Dlouhé vlasy)";
                    break;
                default:
                    echo "Profilová Ikona";
                    break;
            }
        }

        $k = 1;
        for($i = 1;$i <= ceil($pocetSouboru/3); $i++)
        {
                echo "<tr>";
                    for($j = 1; $j <= 3; $j++)
                    {
                        if(file_exists("default/$k.png"))
                        {
                            echo "<td>";
                            echo '<label for="checkboxVychoziProfilovaIkona'.$k.'">';

                                echo '<img src="/users/default/'.$k.'.png" alt="vychoziProfilovaIkona'.$k.'" width="256" class="defaultPFP"></label>
                                      <input class="defaultInputPFP" type="radio" id="checkboxVychoziProfilovaIkona'.$k.'" name="defaultPFP" value="'.$k.'"';if($k==1){echo "checked";} echo '.">';
                                        echo '<label for="checkboxVychoziProfilovaIkona'.$k.'">';
                                        labelPFP($k);
                                        echo '</label>';
                            echo "</td>";
                        }
                        if(($k+1==$pocetSouboru && $pocetSouboru%3==0) || ($pocetSouboru%3!=0 && $k == $pocetSouboru))
                        {
                            echo "<td>";
                            echo '<label for="checkboxVlastniProfilovaIkona"><img src="/users/default/camera.png" alt="vlastniProfilovaIkona" width="256" class="defaultPFP"></label>
                                  <input class="defaultInputPFP" type="radio" id="checkboxVlastniProfilovaIkona" name="defaultPFP" value="' .$k.'"><label for="checkboxVlastniProfilovaIkona">Vlastní Profilová ikona</label>';
                            echo '<input  id="uploadPFP" type="file" name="uploadPFP" accept="'.implode(",",$allowedTypes).'">';
                            echo "</td>";
                        }
                        $k++;
                    }
            echo "<tr>";
        }
        echo "";
        echo "</form>";
        ?>
    </tr>
    </table>
    <input type='submit' name="submit" value="Změnit profilový obrázek">
    </form>













<?php
$dbconnect -> close();
include("../html_bottom.phtml");
?>