<?php
$title = "Nastavení";
include("../html_top.phtml");
include("../nav.phtml");
//echo $pocetSouboru = count(scandir("/users/default/"));

?>

<table id="settingsPFPSelect" ">
    <tr>
        <?php
        for($i = 1;$i <= 3; $i++)
        {
        echo "<td>";
        echo '<img src="/users/default/'.$i.'.png" alt="vychoziProfilovyObrazek'.$i.'" width="256px" class="defaultPFP">';
        echo "</td>";
        }
        ?>
    </tr>
    <tr>
        <?php
        for($i = 4;$i <= 5; $i++)
        {
            echo "<td>";
            echo '<img src="/users/default/'.$i.'.png" alt="vychoziProfilovyObrazek'.$i.'" width="256px" class="defaultPFP">';
            echo "</td>";
        }
        ?>
    </tr>
</table>


















<?php
include("../html_bottom.phtml");
?>